### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by frontzekkarl** [timplab/Cas9Enrichment#2]
Hello

Thanks for the very detailed code. I was re-calculating some of the results and came up with slightly higher coverages compared to those outlined in Table S2 from the paper. For instance, KRAS_for, using the bed file (chr12 25237978 25254719) on SRR10729099 first with minimap2_alignment.sh then bamfilter.sh with the standard settings yields a mean coverage of 262 instead of 254. Similar results are obtained with BRAF (587x compared to 569x). 

Any help is appreciated.

Karl

**Comment by gilfunk** [comment]
hi Karl  -  
  glad the code worked for you  , 
   this is probably because of some quality filtering.  Sometime I removed all supplementary alignments.  In the case of the supp table I think I plotted only unique alignments, which may lead to this small difference in average coverage.
